### ISSUE TITLE
Add requirements.txt from `pip freeze` for easier installation

### ISSUE THREAD

**Issue by rustberry** [omarcostahamido/PVM#10]
Low priority for now.

**TODO**
- [x] Add requirements.txt
- [x] update README.md

**Comment by omarcostahamido** [comment]
Yes, I like that, even though it is pretty short list of dependencies.
Can you include in the todo list also updating the readme? Note: even if the instructions are only to now include the installation command with the txt, can you please still reference the python dependencies? Maybe this means updating the first section.

**Comment by omarcostahamido** [comment]
@rustberry I've just updated your OP with a short TODO list.
This one is pretty straight forward. Since you already have 2 other issues assigned, maybe @KaneBetter would like to take this issue as a _warmup_ until he finds an issue he would like to focus on?

**Comment by omarcostahamido** [comment]
this was fixed by #14
