### ISSUE TITLE
Investigate buffer deadlock prevented issues.

### ISSUE THREAD

**Issue by SSSSam141** [omarcostahamido/PVM#11]
When playing jellyfish video, it will pause by the issue of buffer deadlock prevented for serveral times. 

- [x] Figure out what happens when buffer deadlock prevented protection occurs.
- [x] #12 
- [ ] Decrease the occurrence of buffer deadlock prevented.

**Comment by omarcostahamido** [comment]
Thank you @SSSSam141 for opening this issue. And so it begins... :)
Fyi, the website where you download that jellyfish sample video includes different compression renders that you may also try in your experiments. 
Good luck, and please keep us posted.

**Comment by omarcostahamido** [comment]
@SSSSam141 please feel free to share here some the things you've been trying.

**Comment by KaneBetter** [comment]
Just find out that if you run `sudo apt install vlc` in the terminal.
After that, the error message disappeared.
However, this still needs to be proven by others.

**Comment by SSSSam141** [comment]
I have tried to run vlc to play the video: jellyfish without using Max. The problem was still there so we can make sure that the cause lies in the part of VLC. I have checked that our Raspeberry pi model is 4 (cmd: `cat /proc/device-tree/model` ), its system is  bullseye 11 (cmd: `cat /etc/os-release`), and the vlc version is 3.0.16 (cmd: `vlc -v`).  
Also, we can use debug mode for the vlc, change line 6 at pvm.py file: `inst = vlc.Instance('--verbose 2')`, which will be more convenient for getting more information when debugging.

I tried to upgrade the version of VLC but the buffer deadlock prevented message is still there. 
The completely remove and reinstall VLC commands: In a terminal, run:
`sudo apt-get remove --purge vlc`
`sudo apt-get autoremove`
`sudo apt-get autoclean`
`sudo apt-get install vlc`
Done. 
Thus, reinstall the vlc with the latest version does not help to solve the problem.

The error message: `mmal_xsplitter vout display error: Failed to open Xsplitter:mmal_vout module` happens earlier than the buffer deadlock prevent issue #12 and the buffer deadlock prevent is an error of main decoder error. The mmal_vout is the decoder of vlc which failed to open, so that I think we should solve the problem of #12 first then we can see whether this problem is still there. I will move to see #12 first.

**Comment by omarcostahamido** [comment]
> Just find out that if you run sudo apt install vlc in the terminal.
After that, the error message disappeared.

huh... that's strange.

> I have tried to run vlc to play the video: jellyfish without using Max. The problem was still there so we can make sure that the cause lies in the part of VLC.

Nice.

> Thus, reinstall the vlc with the latest version does not help to solve the problem.

Thx for testing this. Please remind me: is bullseye 11 the latest raspberrypiOS?

> The error message: mmal_xsplitter vout display error: Failed to open Xsplitter:mmal_vout module happens earlier than the buffer deadlock prevent issue https://github.com/omarcostahamido/PVM/issues/12 and the buffer deadlock prevent is an error of main decoder error. The mmal_vout is the decoder of vlc which failed to open, so that I think we should solve the problem of https://github.com/omarcostahamido/PVM/issues/12 first then we can see whether this problem is still there. I will move to see https://github.com/omarcostahamido/PVM/issues/12 first.

Perfect! Prioritizing :) Feel free to change the label on #12 to `High`. Also, add it here as a step on the TODO list.

**Comment by SSSSam141** [comment]
@omarcostahamido Bullseye 11 is the latest version for raspberryPiOS.

**Comment by SSSSam141** [comment]
After I have reinstalled the os with the old version buster 10, the problem still exists. I will try to find the cause now.

**Comment by omarcostahamido** [comment]
@SSSSam141 any updates on this?

**Comment by SSSSam141** [comment]
> @SSSSam141 any updates on this?

@omarcostahamido The new media player: OMXPlayer does not have this issue. I think we can close this issue.

**Comment by omarcostahamido** [comment]
Then I suggest closing this issue with the PR that makes that transition too! #19
