### ISSUE TITLE
Burn a brand-new rpi image on a micro SD card

### ISSUE THREAD

**Issue by rustberry** [omarcostahamido/PVM#13]
Burn a brand-new rpi image on the micro SD card and set up the project from scratch, to make sure we've covered all the needed dependencies.
This requires a micro SD card reader or micro SD card adaptor since I have an SD card port on my laptop.

**Comment by omarcostahamido** [comment]
@rustberry I just simplified the issue name, and move the longer version into the issue OP - thx for creating it.

if anything else, it might be a good to add new and updated versions of the OS so that we might benefit from relevant updates that might have come out in the meantime.

**Comment by omarcostahamido** [comment]
@rustberry can we consider this issued mostly fixed given the work reported in #12 ?
I would still suggest that this issue could be closed with the addition on the README of the complete instructions on how to install and setup the proper OS version. Can you do that and create a PR including the message `this fixes #13`?

**Comment by omarcostahamido** [comment]
_bump_

just looking around the high priority issues and trying to figure out when they'll be closed.

**Comment by rustberry** [comment]
Yeah, I think this could be closed soon. After we finally decided to use OXMPlayer I will update the related instructions.

**Comment by SSSSam141** [comment]
Done.

**Comment by omarcostahamido** [comment]
@SSSSam141 could you please close this issue with the PR/commit that contains the added instructions?

**Comment by omarcostahamido** [comment]
this was closed by #17
