### ISSUE TITLE
Update project `merge` settings

### ISSUE THREAD

**Issue by rustberry** [omarcostahamido/PVM#15]
Hi @omarcostahamido and @gggfffsss, this would be something that only the owner of the repository could do.

The first is to [restrict merging options](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests). Specifically, it would be ideal to only allow "squash merging". My classmates all agree that this is our preferred way for a clear commit history. If you have any other merging preferences we could also talk about them. The result would be like below:
![image](https://user-images.githubusercontent.com/34592958/195220278-b5cc8a6f-68ac-46c2-a142-61d384fe51a1.png)

---
The second would be to add some protection rules to the main branch. Kindly follow the instructions on [this link](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) to find to location of the setting and it would be exactly like this in the end:
![image](https://user-images.githubusercontent.com/34592958/195221830-f0204170-7932-4a84-9b10-c9f8c3a38024.png)

This rule would make sure that any pull requests cannot be merged into the main branch unless it gets at least one approving review from others.

**Comment by omarcostahamido** [comment]
Done and Done.
Thx @rustberry
