### ISSUE TITLE
video files location

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#20]
Following this comment [here](https://github.com/omarcostahamido/PVM/commit/384f329f6767b22971e0ecac7972c80c5da88e3e#r87609305), I'm open to suggestions as to improve 
- [ ] the best location for the video files (it may be beneficial not to be inside `/PVM/` so that one can update the software and not have to re-transfer the video files)
- [ ] the best way to transfer the video files into the rpis
- [ ] readme instructions on this

**Comment by KaneBetter** [comment]
For the first TODO, I think if the video is in the folder /Video/ will be nice.
Second TODO, If I were to implement it, I would use a different strategy for different file sizes, using Git repo for small files and a direct SD card copy for large files.
