### ISSUE TITLE
Improving `set_position` command

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#3]
Currently one can set the position of each display in seconds. This is great even because it allows for floating point number precision of milliseconds even. However, there are some situation where this offset would be better described in terms of frames. Additionally, being able to set relative position, as in from 0.0 (start) to 1.0 (end) might also be helpful when the user simply doesn't know the length of each file. Current command value parsing [line 66 67](https://github.com/omarcostahamido/PVM/blob/700b72b6a9ea928fb8d65e426845d87cfc5f9db4/pvm.py#L66-L67) is retrieving only one value, when in fact it could already retrieve a list of values (the rest of the message). Could this be a good opportunity to explore this space?

- [ ] is current `set_position` command enough, or do we need to create new commands for the new features?
- [ ] allow setting position by frame
- [ ] allow setting position relatively (0.0-1.0)

**Comment by omarcostahamido** [comment]
@KaneBetter can we set the position in frames, besides seconds?

**Comment by KaneBetter** [comment]
Yes, `set_position` can accept float, e.g 0.033. This means if you want to set the video to frame 1, you need to calculate the time(0.033) based on the fps(30fps), which is not very convenient.
So, I create this https://github.com/omarcostahamido/PVM/pull/52/commits/c33320dcb17012f752c1e017736da74e9aed998d to add set_frame UDP command prase logic. But the MAX part is unchanged.

**Comment by KaneBetter** [comment]
For point 3, we need to add a button called relative_set_position(0.0-1.0)
See here, https://github.com/omarcostahamido/PVM/pull/52/commits/160cb4109a67336e424a6d4f8040cdb159c92905

**Comment by KaneBetter** [comment]
> Current command value parsing [line 66 67](https://github.com/omarcostahamido/PVM/blob/700b72b6a9ea928fb8d65e426845d87cfc5f9db4/pvm.py#L66-L67) is retrieving only one value, when in fact it could already retrieve a list of values (the rest of the message). Could this be a good opportunity to explore this space?

Yeah, it depends on what is the rest of the message.

**Comment by omarcostahamido** [comment]
> So, I create this https://github.com/omarcostahamido/PVM/commit/c33320dcb17012f752c1e017736da74e9aed998d to add set_frame UDP command prase logic. But the MAX part is unchanged.

But it needs to be changed, right? You need help with that?

> For point 3, we need to add a button called relative_set_position

`set_relative_position`?

**Comment by omarcostahamido** [comment]
as I've proposed on #53 can we please use `set_position` for the relative position (0.-1.), and then `set_sposition` and `set_fposition` for setting in absolute seconds and frames?

**Comment by KaneBetter** [comment]
> as I've proposed on #53 can we please use `set_position` for the relative position (0.-1.), and then `set_sposition` and `set_fposition` for setting in absolute seconds and frames?

Done in https://github.com/omarcostahamido/PVM/pull/52/commits/697d8193fb0a4db023da9a62a623faef1d99ef81
