### ISSUE TITLE
Two videos control python script

### ISSUE THREAD

**Issue by KaneBetter** [omarcostahamido/PVM#30]
- Play two different videos on two displays.
- Control two videos at the same time.
- Update README.md about how to set two videos.

For now, let's split the python file into two and consider whether to merge them later.
Created branch called [TwoVideosControl](https://github.com/omarcostahamido/PVM/tree/TwoVideosControl)

**Comment by omarcostahamido** [comment]
alright, let's go! I'm excited 😄

**Comment by KaneBetter** [comment]
Making the pull request #31 into a draft.
We plan to use another approach to realize two video control.

**Comment by KaneBetter** [comment]
This is not the case with the latest version.
