### ISSUE TITLE
RESET & PLAY logic rewrite.

### ISSUE THREAD

**Issue by SSSSam141** [omarcostahamido/PVM#32]
The current RESET function has some logic problems: when click twice reset button, the video will start to play.
The current PLAY function has some logic problems: when click multiple times when video is playing, the video will crash.
Bugs need to be fixed

**Comment by SSSSam141** [comment]
Done

**Comment by omarcostahamido** [comment]
?

**Comment by KaneBetter** [comment]
No longer needed.

**Comment by omarcostahamido** [comment]
@KaneBetter it got fixed? Do you know how/why?
