### ISSUE TITLE
Script to sync time in multiple Raspberry Pis

### ISSUE THREAD

**Issue by KaneBetter** [omarcostahamido/PVM#39]
Here are some possible solutions:

- https://stackoverflow.com/questions/59159209/how-to-run-a-python-script-on-multiple-raspberry-pi-3-simultaneously
- https://forums.raspberrypi.com/viewtopic.php?t=194468

Resource:

- [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol)

**Comment by omarcostahamido** [comment]
ooo, I like where this is going 😄 
please see also what I wrote [here](https://github.com/omarcostahamido/PVM/issues/35#issuecomment-1312552703).
