### ISSUE TITLE
2 monitors are not synchronized

### ISSUE THREAD

**Issue by KaneBetter** [omarcostahamido/PVM#42]
When we test two videos' python script, we found out that r=press start once and then pause and then press start again has a certain chance of causing the two monitors to be out of sync.

TODO: Reproduce the bug first, then determine why the bug occurred

**Comment by SSSSam141** [comment]
The 2 media.position functions are totally 0.03s ~ 0.04s, at most time the offset of the 2 videos are under this range and we can consider them synchronized while as the video continue to loop, the offset of them becomes larger. I will investigate more into this problem and try to find out what is the cause of this problem.

**Comment by SSSSam141** [comment]
After checking the source code of set_position() function, it is "Set the video to playback position to `position` seconds from the start of the video", which should set to the past time not the future time. Then I change the logic for media 1 and media 2, only set the media which is playing relatively faster back to the position where media is playing relatively slower. Then now the 2 videos are synchronized.

**Comment by omarcostahamido** [comment]
> Then I change the logic for media 1 and media 2, only set the media which is playing relatively faster back to the position where media is playing relatively slower. Then now the 2 videos are synchronized.

🐢 🐇 

@SSSSam141 
where exactly did you do that? the PR still doesn't seem to be linked here.

**Comment by KaneBetter** [comment]
This is not the case with the latest version.

**Comment by omarcostahamido** [comment]
good to hear!
