### ISSUE TITLE
Frame setting feature implementation

### ISSUE THREAD

**Issue by xrk-git** [omarcostahamido/PVM#43]
Acquire the playing video's frame rate and set the Omxplayer exhibition frame rate.

**Comment by omarcostahamido** [comment]
@xrk-git where/how did you complete/fix this?
could you please use the keywords `this fixes #43` on the PR that fixes this before merge? That way it will create a link here and close this with that PR. This saves you time to manually close an issue, AND creates a link that makes it easier to go back and understand where exactly were the changes that fixed it. (you can still go there and write `this refers to #43` just to create that link)
thank you

**Comment by xrk-git** [comment]
This fixes #47

**Comment by omarcostahamido** [comment]
@xrk-git the PR fixes the issue, not the other way around.
I'm going to edit the OP on #47 for you to include those words and you'll see the difference 😉
