### ISSUE TITLE
An alternative way to get PVM working directory

### ISSUE THREAD

**Issue by rustberry** [omarcostahamido/PVM#45]
https://github.com/omarcostahamido/PVM/blob/ef4cff7ecba3fe27613c1742c74051db0de88c47/pvm.py#L34

Currently, we're hard coding it, but we could use the $HOME variable to resolve the path dynamically.

**Comment by omarcostahamido** [comment]
this refers to #8 

@rustberry do you want to do a thorough review of this and use your PR to 
`this fixes #45`
`this fixes #8`
if you know what I mean?
