### ISSUE TITLE
Going out of sync!

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#5]
under some circumstance devices, that have been triggered to start at the same time, go out of sync.
@gggfffsss was this still happening with the latest version?
This issue needs to be further investigated... and, it is still happening, it needs to be fixed.

Adding some more context:
- @gggfffsss confirmed that often times, but not consistently, frames are skipped during the first few seconds of starting to play a clip.
- we've noticed that it happens less often when playback speed is less than normal speed (`1.0`).
- one of the previous workarounds used was forcing all devices to go to clip position `0` every _x_ minutes. This is what is currently achieved with the top right portion of the `pvm.maxpat` control patch.
- another workaround was to start devices to play clips at a speed slower than normal speed (`< 1.0`) and progressively increase their speed up to normal speed in _x_ number of steps during _y_ seconds. This is what is currently achieved with the bottom right portion of the `pvm.maxpat` control patch.

**Comment by omarcostahamido** [comment]
Issue #11 is focusing on the `buffer deadlock` problem which might be what causes the videos to go out of sync.

**Comment by omarcostahamido** [comment]
@SSSSam141 I know you focused on the `buffer deadlock` issue, which could be the reason for things going out of sync. In any case, I would like to ask you to confirm that synced videos is really no longer an issue and that omxplayer has solved it all. Best way to confirm that could be with the newly added [examples](https://github.com/omarcostahamido/PVM/tree/main/examples), I would suggest 😉 
If all is good in this domain then this issue could be closed.

**Comment by KaneBetter** [comment]
Find some projects for sync omxplayer.
https://github.com/turingmachine/omxplayer-sync
https://github.com/bmoren/node-omxplayer-sync

**Comment by omarcostahamido** [comment]
woah, thank you for finding those @KaneBetter !
I'm boosting this issue to `HIGH`. I'd love to see this being closed next, before the dual screen issue which will bring added complexity here.
take it away!

**Comment by KaneBetter** [comment]
> woah, thank you for finding those @KaneBetter ! I'm boosting this issue to `HIGH`. I'd love to see this being closed next, before the dual screen issue which will bring added complexity here. take it away!

We still need to reproduce this issue first. Maybe this issue doesn't exist in OMXPlayer.
If this issue does exist, we have two options to choose from.
One is to send a timestamp with the start function.
Two is to let each Raspberry Pi talk to the other.

**Comment by KaneBetter** [comment]
It seems omxplayer and python processes themselves run smoothly in each RPI. The average time for the system to execute the command is 70ms.
We also observed this issue #35  in our tests. So we think bringing this #35  up is an excellent solution.

**Comment by KaneBetter** [comment]
#38 fixes this.
