### ISSUE TITLE
Two different PORT approach

### ISSUE THREAD

**Issue by KaneBetter** [omarcostahamido/PVM#51]
#50 
The main idea is to give pvm.py a port args(which is already there).
So in the `etc/xdg/lxsession/LXDE-pi/autostart`
```
@lxterminal -e sh $HOME/PVM/launch 8001
@lxterminal -e sh $HOME/PVM/launch 8002
```
Ang in the `max-init.txt` will be 
```
1, jellyfish720.mp4 192.168.0.235 8001;
2, jellyfish720.mp4 192.168.0.235 8002;
```
And if we run pvm.py without port arg the default port is 8001.

**Comment by omarcostahamido** [comment]
definitely a possibility. The question that remains is: will it work well on the RPI to have 2 `pvm.py` running at the same time? Will the 2 OSC servers compete with each other and add more latency to the reception of commands?...
