### ISSUE TITLE
`omx_player` specific version reference

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#55]
@KaneBetter can you make a release on your https://github.com/KaneBetter/omxplayer repo that we can refer to as the specific version that is compatible with PVM?
Something to consider as an alternative would be to create a git submodule.
Thoughts?

**Comment by KaneBetter** [comment]
Sure, will do.

**Comment by KaneBetter** [comment]
https://github.com/KaneBetter/omxplayer/releases/tag/v1.0.0

**Comment by omarcostahamido** [comment]
thank you!
maybe this could be added to the readme and make that PR resolve this issue?
edit: the readme does need some thorough revision, I am making that a parent issue to this one.
